services:
  anvil:
    build:
      dockerfile: Dockerfile.anvil
    volumes:
      - ./state:/state
    environment:
      ANVIL_STATE: "/state/anvil"
      ANVIL_STATE_INTERVAL: 10
    ports:
      - "8545:8545"
      
  faucet:
    build:
      dockerfile: Dockerfile.faucet
    working_dir: /app
    volumes:
      - ./faucet:/app
    ports:
      - "3000:3000"
    depends_on:
      - anvil

  otterscan:
    image: otterscan/otterscan:v2.6.1
    ports:
      - "3001:80"
    volumes:
      - ./otterscan/config.json:/usr/share/nginx/html/config.json
    environment:
      DISABLE_CONFIG_OVERWRITE: "1"

  ipfs:
    image: ipfs/kubo:v0.17.0
    ports:
      - "4001:4001"
      - "8080:8080"

  sourcify:
    image: ghcr.io/ethereum/sourcify/server:latest
    ports:
      - "5555:5555"
    volumes:
      - ./data/sourcify:/data
      # - ./sourcify/chains.json:/home/app/services/server/dist/sourcify-chains.json
      - ./sourcify/local.js:/home/app/services/server/dist/config/local.js

  sourcify-ui:
    image: ghcr.io/ethereum/sourcify/ui:latest
    ports:
      - "3002:80"
    environment:
      REACT_APP_SERVER_URL: "http://localhost:5555"
      REACT_APP_REPOSITORY_SERVER_URL: "http://localhost:5555"
