services:
  anvil:
    build:
      dockerfile: Dockerfile.anvil
    volumes:
      - ./data/anvil:/state
    environment:
      ANVIL_STATE: "/state/anvil"
      ANVIL_STATE_INTERVAL: 10
      ANVIL_CHAIN_ID: 7566690 # sub -> hex -> decimal
      ANVIL_AUTO_IMPERSONATE: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rpc.entrypoints=websecure"
      - "traefik.http.routers.rpc.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.rpc.middlewares=auth"
      - "traefik.http.services.rpc.loadbalancer.server.port=8545"
      
  faucet:
    build:
      dockerfile: Dockerfile.faucet
    depends_on:
      - anvil
    environment:
      PORT: 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faucet.entrypoints=websecure"
      - "traefik.http.routers.faucet.rule=Host(`faucet.${DOMAIN}`)"
      - "traefik.http.routers.faucet.middlewares=auth"
      - "traefik.http.services.faucet.loadbalancer.server.port=80"

  otterscan:
    image: otterscan/otterscan:v2.6.1
    volumes:
      - ./config/otterscan/config.json:/usr/share/nginx/html/config.json
    environment:
      DISABLE_CONFIG_OVERWRITE: "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explorer.entrypoints=websecure"
      - "traefik.http.routers.explorer.rule=Host(`explorer.${DOMAIN}`)"
      - "traefik.http.routers.explorer.middlewares=auth"
      - "traefik.http.services.explorer.loadbalancer.server.port=80"

  sourcify:
    image: ghcr.io/ethereum/sourcify/server:staging
    volumes:
      - ./data/sourcify:/data
      - ./config/sourcify/chains.json:/home/app/services/server/dist/sourcify-chains.json
      - ./config/sourcify/local.js:/home/app/services/server/dist/config/local.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sourcify.entrypoints=websecure"
      - "traefik.http.routers.sourcify.rule=Host(`sourcify.${DOMAIN}`)"
      - "traefik.http.routers.sourcify.middlewares=auth"
      - "traefik.http.services.sourcify.loadbalancer.server.port=5555"

  traefik:
    image: "traefik:v3.1"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik/usersFile:/etc/traefik/usersFile"
      - "./data/traefik/acme:/acme"
    command:
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
      - "--certificatesresolvers.myresolver.acme.email=mpalhas@gmail.com"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.storage=/acme/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.auth.basicauth.usersFile=/etc/traefik/usersFile"
