services:
  anvil:
    build:
      dockerfile: Dockerfile.anvil
    volumes:
      - ./data/anvil:/state
    environment:
      ANVIL_STATE: "/state/anvil"
      ANVIL_STATE_INTERVAL: 10
      ANVIL_CHAIN_ID: 7566690 # sub -> hex -> decimal
      ANVIL_AUTO_IMPERSONATE: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rpc.entrypoints=web"
      - "traefik.http.routers.rpc.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.rpc.loadbalancer.server.port=8545"
      
  faucet:
    build:
      dockerfile: Dockerfile.faucet
    working_dir: /app
    command: ["bun", "next", "dev", "-p", "80"]
    volumes:
      - ./faucet:/app
    depends_on:
      - anvil
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.faucet.entrypoints=web"
      - "traefik.http.routers.faucet.rule=Host(`faucet.${DOMAIN}`)"
      - "traefik.http.services.faucet.loadbalancer.server.port=80"

  otterscan:
    image: otterscan/otterscan:v2.6.1
    volumes:
      - ./config/otterscan/config.json:/usr/share/nginx/html/config.json
    environment:
      DISABLE_CONFIG_OVERWRITE: "1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explorer.entrypoints=web"
      - "traefik.http.routers.explorer.rule=Host(`explorer.${DOMAIN}`)"
      - "traefik.http.services.explorer.loadbalancer.server.port=80"

  sourcify:
    image: ghcr.io/ethereum/sourcify/server:staging
    ports:
      - "5555:5555"
    volumes:
      - ./data/sourcify:/data
      - ./config/sourcify/chains.json:/home/app/services/server/dist/sourcify-chains.json
      - ./config/sourcify/local.js:/home/app/services/server/dist/config/local.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sourcify.entrypoints=web"
      - "traefik.http.routers.sourcify.rule=Host(`sourcify.${DOMAIN}`)"
      - "traefik.http.services.sourcify.loadbalancer.server.port=5555"

  traefik:
    image: "traefik:v3.1"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
